### ISSUE TITLE
Connection reset using websocket

### ISSUE THREAD

**Issue by dosas** [phimuemue/openschafkopf#2] opened 2024-11-01 09:39 UTC
```
openschafkopf$ ./target/release/openschafkopf websocket
Listening on: 127.0.0.1:8080
Incoming TCP connection from: 127.0.0.1:38858
Error in accepting tcpstream: WebSocket protocol error: No "Connection: upgrade" header
Incoming TCP connection from: 127.0.0.1:38862
Error in accepting tcpstream: WebSocket protocol error: No "Connection: upgrade" header
Incoming TCP connection from: 127.0.0.1:38876
Error in accepting tcpstream: WebSocket protocol error: No "Connection: upgrade" header
Incoming TCP connection from: 127.0.0.1:38892
Error in accepting tcpstream: WebSocket protocol error: No "Connection: upgrade" header
Incoming TCP connection from: 127.0.0.1:38902
Error in accepting tcpstream: WebSocket protocol error: No "Connection: upgrade" header
Incoming TCP connection from: 127.0.0.1:38906
Error in accepting tcpstream: WebSocket protocol error: No "Connection: upgrade" header
Incoming TCP connection from: 127.0.0.1:38922
Error in accepting tcpstream: WebSocket protocol error: No "Connection: upgrade" header
Incoming TCP connection from: 127.0.0.1:38930
Error in accepting tcpstream: WebSocket protocol error: No "Connection: upgrade" header
Incoming TCP connection from: 127.0.0.1:38942
Error in accepting tcpstream: WebSocket protocol error: No "Connection: upgrade" header
Incoming TCP connection from: 127.0.0.1:38946
Error in accepting tcpstream: WebSocket protocol error: No "Connection: upgrade" header
```

Notes:
* firefox 128.3.1esr (64-bit)
* rustc 1.82.0
* lessc 3.9.0
* debian 12

**Comment by phimuemue** [comment] 2024-11-06 19:16
I'm sorry to hear this, but sadly I cannot reproduce the problem on my machine.

Since I do not often work on `websocket`, could you guide me through what you did exactly?

For clarity (and if I recall correctly, that's how I intended it back then), I assume you compiled `site.ts` to `site.js` by using `tcs`, run `openschafkopf websocket`, and open `site.html` in a browser. Is this correct?

**Comment by dosas** [comment] 2024-11-06 19:20
Hmm, I might be missing some steps here.

I executed the description from the README:
```
cargo build --release
./target/release/openschafkopf websocket
```

and then tried to open 127.0.0.1:8080 in firefox

**Comment by phimuemue** [comment] 2024-11-06 19:24
Ah, na, that won't work. I must update examples/websocket.sh to include the necessary steps.

Note that the whole `websocket` thing is in a very prototype stage. It can surely be used to actually play, but that requires some work.

**Comment by phimuemue** [comment] 2024-11-06 19:38
If you don't object, I'd like to close this.

**Comment by dosas** [comment] 2024-11-06 19:40
I tried transpiling it using `tcs`:

```
npm install typescript --save-dev
npx tsc ./lib/tools/site/site.ts
./target/release/openschafkopf websocket
firefox ./lib/tools/site/site.html
```

now I at least get some connection
![image](https://github.com/user-attachments/assets/45851282-98bc-4ae6-adae-a2a7a93e4829)

**Comment by dosas** [comment] 2024-11-06 20:00
> If you don't object, I'd like to close this.

Sure, go ahead.

**Comment by phimuemue** [comment] 2024-11-06 20:13
That looks right. The site should - during load - ask you for a user name.

Try opening the site in four different tabs, then you should see a game taking place. Note that each tab then represents a human player, and I think for each decision I implemented a timeout of 2 seconds so that you have to decide pretty quickly. (As I said... prototype.)

**Closed** 2024-11-06 20:51 UTC
